services:
  - type: web
    name: elite-shop
    runtime: static
    buildCommand: npm install && npm run build --workspace apps/web
    staticPublishPath: apps/web/dist
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /api/*
        destination: https://elite-rzpk.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
